Repository DDD-Community/DailyChaCha, pull requests merged in 2022-07, with the labels that each got.

#9 [UI] 로그인 화면 로직 및 UI 구현
  .gitignore
  .package.resolved
  DailyChaCha/DailyChaCha.entitlements
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/apple_logo.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/apple_logo.imageset/apple_logo.pdf
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_bg_gym.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_bg_gym.imageset/img_bg_gym.pdf
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_character.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_character.imageset/img_character.pdf
  DailyChaCha/DailyChaCha/Resources/Base.lproj/LaunchScreen.storyboard
  DailyChaCha/DailyChaCha/Resources/Info.plist
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/TokenInfo.swift
  DailyChaCha/DailyChaCha/Sources/Domain/UseCases/LoginUseCase.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Repositories/LoginRepository.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Services/BaseService.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Services/LoginService.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Login/LoginInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Login/LoginViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Root/RootBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Root/RootRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Root/RootViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/ViewController.swift
  Project.swift
Labels: UI

#11 [Core] token 저장 로직 및 로그인 후 온보딩 화면 RIBs 연결
  DailyChaCha/DailyChaCha/Sources/Application/Managers/UserDefaultsManager.swift
  DailyChaCha/DailyChaCha/Sources/Application/Managers/UserInfoManager.swift
  DailyChaCha/DailyChaCha/Sources/Application/Protocols/LocalPersistable.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/TokenInfo.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/UserInfo.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Models/Login/LoginState.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Services/BaseService.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Login/LoginBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Login/LoginInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Login/LoginRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Login/LoginViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/OnboardingBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/OnboardingInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/OnboardingRouter.swift
Labels: core

#14 [UI] 온보딩 API 연결, 운동 수정 화면 구현
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/ic_arr_s_right.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/ic_arr_s_right.imageset/ic_arr_s_right.pdf
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/icon_back.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/icon_back.imageset/icon_back.pdf
  DailyChaCha/DailyChaCha/Sources/Application/CustomView/NavigationBar/NaviBackBar.swift
  DailyChaCha/DailyChaCha/Sources/Application/CustomView/NavigationBar/NaviBackBar.xib
  DailyChaCha/DailyChaCha/Sources/Application/CustomView/NavigationBar/NaviCloseBar.swift
  DailyChaCha/DailyChaCha/Sources/Application/CustomView/NavigationBar/NaviCloseBar.xib
  DailyChaCha/DailyChaCha/Sources/Application/Extensions/Rx/Ex+Rx+UITableView.swift
  DailyChaCha/DailyChaCha/Sources/Application/Managers/UserInfoManager.swift
  DailyChaCha/DailyChaCha/Sources/Application/Protocols/CellModelable.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/EditRoutineEntity.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/OnboardingEntity.swift
  DailyChaCha/DailyChaCha/Sources/Domain/UseCases/OnboardingUseCase.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Repositories/Mock/Onboarding/OnboardingCompleteRepository.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Repositories/Mock/Onboarding/OnboardingNewbieRepository.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Repositories/Mock/Onboarding/OnboardingOldbieRepository.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Repositories/OnboardingRepository.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Services/OnboardingService.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/EditRoutineBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/EditRoutineInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/EditRoutineRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Date/EditDateBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Date/EditDateInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Date/EditDateRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Date/EditDateViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Date/EditRoutineComponent+Date.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/EditRoutine.storyboard
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Goal/EditGoalBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Goal/EditGoalInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Goal/EditGoalRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Goal/EditGoalViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Goal/EditRoutineComponent+Goal.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Start/EditRoutineComponent+Start.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Start/EditStartBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Start/EditStartInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Start/EditStartRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Start/EditStartViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Start/Views/EditStartCell.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Time/EditRoutineComponent+Time.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Time/EditTimeBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Time/EditTimeInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Time/EditTimeRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/EditRoutine/Scenes/Time/EditTimeViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/OnboardingInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/OnboardingRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/1. Goal/OnboardingGoalInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/1. Goal/Views/OnboardingGoalWriteCell.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/2. Date/OnboardingDateInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/2. Date/Views/OnboardingDateSelectCell.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/3. Time/OnboardingTimeInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/3. Time/Views/Views/OnboardingTimeSelectView.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/3. Time/Views/Views/OnboardingTimeView.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/4. Alert/OnboardingAlertInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/4. Alert/OnboardingAlertViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/Scenes/5. Welcome/OnboardingWelcomeInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Root/RootViewController.swift
Labels: UI

#16 [UI] 운동 시작하기 화면
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_bottom_sheet.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_bottom_sheet.imageset/img_bottom_sheet.pdf
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_character_routine.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_character_routine.imageset/img_character_routine.pdf
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_object_box.imageset/Contents.json
  DailyChaCha/DailyChaCha/Resources/Assets.xcassets/img_object_box.imageset/img_object_box.pdf
  DailyChaCha/DailyChaCha/Resources/Lotties/lottie-rotating-light.json
  DailyChaCha/DailyChaCha/Sources/Application/CustomView/CircleView.swift
  DailyChaCha/DailyChaCha/Sources/Application/Extensions/Ex+Date.swift
  DailyChaCha/DailyChaCha/Sources/Application/Extensions/Ex+Numeric.swift
  DailyChaCha/DailyChaCha/Sources/Application/Extensions/Ex+String.swift
  DailyChaCha/DailyChaCha/Sources/Application/Managers/UserInfoManager.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/MoyaEntity.swift
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/RoutineEntity.swift
  DailyChaCha/DailyChaCha/Sources/Domain/UseCases/RoutineUseCase.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Repositories/RoutineRepository.swift
  DailyChaCha/DailyChaCha/Sources/Platform/Services/RoutineService.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Routine.storyboard
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/RoutineBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/RoutineInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/RoutineRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/1. RoutineWait/RoutineComponent+Wait.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/1. RoutineWait/RoutineWaitBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/1. RoutineWait/RoutineWaitInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/1. RoutineWait/RoutineWaitRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/1. RoutineWait/RoutineWaitViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/2. RoutineStart/RoutineComponent+Start.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/2. RoutineStart/RoutineStartBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/2. RoutineStart/RoutineStartInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/2. RoutineStart/RoutineStartRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/2. RoutineStart/RoutineStartViewController.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/3.RoutineResult/RoutineComponent+Result.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/3.RoutineResult/RoutineResultBuilder.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/3.RoutineResult/RoutineResultInteractor.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/3.RoutineResult/RoutineResultRouter.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Routine/Scenes/3.RoutineResult/RoutineResultViewController.swift
  Project.swift
  vendor/RxAlert/.gitignore
  vendor/RxAlert/Package.resolved
  vendor/RxAlert/Package.swift
  vendor/RxAlert/README.md
  vendor/RxAlert/Sources/RxAlert/AlertAction.swift
  vendor/RxAlert/Sources/RxAlert/OutputAction.swift
  vendor/RxAlert/Sources/RxAlert/RxAlert.swift
  vendor/RxAlert/Sources/RxAlert/UIViewController+.swift
  vendor/RxAlert/Tests/RxAlertTests/RxAlertTests.swift
Labels: UI

#17 [bug] 온보딩 - done으로 떨어지면 complete 실행하는 로직으로 변경
  DailyChaCha/DailyChaCha/Sources/Domain/Entities/OnboardingEntity.swift
  DailyChaCha/DailyChaCha/Sources/Presentation/Scenes/Onboarding/OnboardingRouter.swift
Labels: bug
